spring:
  application:
    name: micr-dataservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/licai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: bjpowernode
  #redis配置
  redis:
    host: localhost
    port: 6379
    #password: 123456

#dubbo
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.bjpowernode.dataservice.service
  protocol:
    name: dubbo
  provider:
    timeout: 5000

#配置mybatis
mybatis:
  configuration:
    #日志，输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper文件的位置
  mapper-locations: classpath:mappers/**/*.xml